In [1]:
#from sklearn.model_selection import train_test_split
#from sklearn.datasets import load_iris
#from sklearn.naive_bayes import GaussianNB

In [2]:
#iris = load_iris()

In [3]:
#X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=0)

In [4]:
#clf = GaussianNB()

In [5]:
#clf.fit(X_train, y_train)

In [6]:
#clf.score(X_test, y_test)

# Dataset: MINIST

In [7]:
import pandas as pd
import numpy as np
import matplotlib as plt

Data processing

In [8]:
train_set = pd.read_csv("./data/MNIST/mnist_train.csv", header=None).values

In [9]:
train_set

array([[5, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [4, 0, 0, ..., 0, 0, 0],
       ...,
       [5, 0, 0, ..., 0, 0, 0],
       [6, 0, 0, ..., 0, 0, 0],
       [8, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [10]:
train_set[0,:200]

array([  5,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,
        18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 15

In [11]:
train_set.shape

(60000, 785)

In [12]:
train_data_raw = train_set[:, 1:]

In [13]:
train_data_raw[0,:200]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18,
       126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 17

In [14]:
train_data_raw.shape

(60000, 784)

In [15]:
train_data = np.zeros(train_data_raw.shape)

In [16]:
# be careful about sequence
train_data[train_data_raw <= 128] = 0
train_data[train_data_raw > 128] = 1

In [17]:
train_data[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [18]:
train_data = train_data.astype('int64')

In [19]:
train_data[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,

In [20]:
train_label = train_set[:,0]

In [21]:
train_label

array([5, 0, 4, ..., 5, 6, 8], dtype=int64)

In [22]:
train_label.shape

(60000,)

In [23]:
test_set = pd.read_csv("./data/MNIST/mnist_test.csv", delimiter=',', header=None).values

In [24]:
test_set[0, :250], test_set.shape

(array([  7,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0

In [25]:
test_data = test_set[:,1:] 

In [26]:
test_data.shape

(10000, 784)

In [27]:
test_data[0, :250]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [28]:
test_label = test_set[:,0]

In [29]:
test_label

array([7, 2, 1, ..., 4, 5, 6], dtype=int64)

In [30]:
test_label.shape

(10000,)

Caculating Prior probabilities using Bayesian Estimation

In [31]:
class_num = 10
image_feature_num = 784 # 28 * 28 pixel
pr_y = np.zeros((class_num, 1)) # prior pr list
lam = 1 # Laplace smoothing
k = 10 # the number of label
sj = 2 # the number of image features/pixel

In [32]:
train_label_mat = np.mat(train_label)
train_label_mat == 5

matrix([[ True, False, False, ...,  True, False, False]])

In [33]:
np.sum(train_label_mat==5)

5421

In [34]:
# Prior probabilities
for i in range (class_num):
        pr_y[i] = (np.sum(np.mat(train_label)==i) + lam) / ((len(train_label) + k * lam))    

In [35]:
pr_y

array([[0.09871688],
       [0.11236461],
       [0.09930012],
       [0.10218297],
       [0.09736711],
       [0.09035161],
       [0.09863356],
       [0.10441593],
       [0.09751708],
       [0.09915014]])

In [36]:
pr_y = np.log(pr_y)

In [37]:
pr_y

array([[-2.31549932],
       [-2.18600629],
       [-2.30960853],
       [-2.28099025],
       [-2.32926685],
       [-2.40404646],
       [-2.3163437 ],
       [-2.25937302],
       [-2.32772773],
       [-2.31112   ]])

Caculating conditional probabilities

In [38]:
pr_x_y = np.zeros((class_num, image_feature_num, 2)) # 3-dimension

In [39]:
pr_x_y[0][0][0]

0.0

In [40]:
a = train_data[0]

In [41]:
a[0]

0

In [42]:
for i in range(len(train_label)):
    # get ith image pixel and label
    x = train_data[i]
    label = train_label[i]
    # pr_x_y stored the sum number of each image feature(0 or 1) in each label
    for j in range(image_feature_num):
        pr_x_y[label][j][x[j]] += 1

In [43]:
pr_x_y[0][500]

array([5674.,  249.])

In [44]:
for label in range(class_num):
    for j in range(image_feature_num):
        pr_x_y0 = pr_x_y[label][j][0] # conditional pr. of the feature 0
        pr_x_y1 = pr_x_y[label][j][1] # conditional pr. of the feature 1
        
        pr_x_y[label][j][0] = np.log((pr_x_y0 + lam) / (pr_x_y0 + pr_x_y1 + sj))
        pr_x_y[label][j][1] = np.log((pr_x_y1 + lam) / (pr_x_y0 + pr_x_y1 + sj))


In [46]:
pr_x_y

array([[[-1.68790616e-04, -8.68693597e+00],
        [-1.68790616e-04, -8.68693597e+00],
        [-1.68790616e-04, -8.68693597e+00],
        ...,
        [-1.68790616e-04, -8.68693597e+00],
        [-1.68790616e-04, -8.68693597e+00],
        [-1.68790616e-04, -8.68693597e+00]],

       [[-1.48290947e-04, -8.81640850e+00],
        [-1.48290947e-04, -8.81640850e+00],
        [-1.48290947e-04, -8.81640850e+00],
        ...,
        [-1.48290947e-04, -8.81640850e+00],
        [-1.48290947e-04, -8.81640850e+00],
        [-1.48290947e-04, -8.81640850e+00]],

       [[-1.67799312e-04, -8.69282576e+00],
        [-1.67799312e-04, -8.69282576e+00],
        [-1.67799312e-04, -8.69282576e+00],
        ...,
        [-1.67799312e-04, -8.69282576e+00],
        [-1.67799312e-04, -8.69282576e+00],
        [-1.67799312e-04, -8.69282576e+00]],

       ...,

       [[-1.59578713e-04, -8.74305305e+00],
        [-1.59578713e-04, -8.74305305e+00],
        [-1.59578713e-04, -8.74305305e+00],
        ...,
     

Testing the test_set